version: '3.8'

services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:15
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: matdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: